import{useState}from 'react'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
export default function AboutPage(){
const[slide,setSlide]=useState(0)
return(
<>
<Navbar />
<section className='py-5 px-5 bg-light'><div className='row align-items-center g-5'><div className='col-lg-6'><h1 className='fw-light mb-3' style={{fontSize:'clamp(20px,2.5vw,32px)',background:'linear-gradient(110deg,#621DA3 0%,#A038D0 100%)',WebkitBackgroundClip:'text',WebkitTextFillColor:'transparent',backgroundClip:'text'}}>Understanding Cancer Through Data</h1><p className='text-secondary mb-4' style={{lineHeight:1.85,textAlign:'justify'}}>PBCCR (Population Based Cancer Care Registry) is a digital platform designed to collect, manage, and analyze cancer-related data across different regions. It helps in understanding cancer patterns, trends, and risk factors to support better healthcare decisions.</p><div className='d-flex gap-3 flex-wrap'><button className='btn text-white fw-semibold rounded-pill px-4 py-2' style={{background:'linear-gradient(105deg,#611DA2 0%,#A038D0 100%)'}}>Data Visualization</button><button className='btn fw-semibold rounded-pill px-4 py-2' style={{border:'1px solid rgba(200,196,214,0.40)'}}>Contact Us</button></div></div><div className='col-lg-6'><div className='rounded-4 overflow-hidden shadow'><img src='https://api.builder.io/api/v1/image/assets/TEMP/ed9c69417224e009e0736af65413aace9917a893?width=1255' alt='Healthcare technology' className='w-100' style={{height:420,objectFit:'cover'}} /></div></div></div></section>
<section className='py-5 px-5 bg-light'><div className='row g-4'><div className='col-md-6'><div className='pbr-mission h-100 p-5'><h3 className='fw-bold mb-3'>Our Mission</h3><p style={{lineHeight:1.8,color:'rgba(255,255,255,0.92)'}}>Our mission is to improve cancer awareness, early detection, and treatment outcomes by providing accurate and reliable data. We aim to support healthcare professionals, researchers, and policymakers with meaningful insights.</p><a href='/methods' className='text-white fw-semibold mt-3 d-inline-block'>Learn more about our methodology &rarr;</a></div></div><div className='col-md-6'><div className='pbr-vision h-100 p-5'><h3 className='fw-bold mb-3'>Our Vision</h3><p style={{lineHeight:1.8,color:'rgba(255,255,255,0.92)'}}>To build a data-driven healthcare ecosystem where cancer can be detected early, treated effectively, and managed with better planning and awareness.</p></div></div></div></section>
<section className='py-5 px-5 bg-light'><div className='row g-4'><div className='col-md-5'><div className='rounded-4 p-4 h-100' style={{background:'#F6F2FD'}}><div className='d-flex align-items-center gap-3 mb-3'><div className='bg-white rounded-3 d-flex align-items-center justify-content-center' style={{width:40,height:40,boxShadow:'0 1px 2px rgba(0,0,0,0.05)'}}><svg width='18' height='18' viewBox='0 0 18 18' fill='none'><circle cx='9' cy='9' r='8' stroke='#8805A4' strokeWidth='1.5'/></svg></div><h5 className='fw-bold mb-0'>Why PBCCR Matters</h5></div><p className='text-secondary' style={{lineHeight:1.65,textAlign:'justify'}}>Accurate cancer data is essential for improving healthcare systems. PBCCR helps in identifying high-risk areas, tracking trends, and supporting early diagnosis.</p></div></div><div className='col-md-7'><div className='rounded-4 p-4 h-100' style={{background:'#E5E0EC'}}><h5 className='fw-bold mb-3'>What We Do</h5><p className='text-secondary' style={{lineHeight:1.7,textAlign:'justify'}}>We collect population-based cancer data and transform it into useful insights through analysis and visualization. Our platform enables users to explore cancer statistics by age, region, and type, helping in better understanding and planning.</p><div className='row g-2 mt-2'>{['Collection','Analysis','Insights','Outcomes'].map(l=>(<div className='col-6' key={l}><div className='bg-white rounded-3 p-2 text-center'><span className='small fw-semibold text-uppercase' style={{color:'#787585',letterSpacing:0.5}}>{l}</span></div></div>))}</div></div></div></div></section>
<section className='py-5 px-3 text-center' style={{background:'#F6F2FD'}}><h2 className='fw-bold mb-5'>Authorship and Perspective</h2><div className='d-flex justify-content-center gap-4 flex-wrap'><div className='rounded-4 p-4 text-white d-flex flex-column align-items-center gap-3' style={{background:'linear-gradient(135deg,#661FA5 0%,#9E38CC 100%)',width:280}}><div className='rounded-circle overflow-hidden' style={{width:150,height:150,border:'3px solid rgba(255,255,255,0.3)'}}><img src='https://api.builder.io/api/v1/image/assets/TEMP/2d18608c84d5b04c8732533796edc51625e931b4?width=336' alt='Dr Elena' className='w-100 h-100' style={{objectFit:'cover'}} /></div><div className='p-3 rounded-4 w-100 text-center' style={{background:'rgba(255,255,255,0.10)',border:'1px solid rgba(255,255,255,0.20)'}}><p className='fw-bold mb-1'>Dr. Elena Rodriguez</p><p className='small mb-0 opacity-75'>Head of Clinical Oncology</p></div></div><div className='rounded-4 p-4 text-white d-flex align-items-end' style={{background:'linear-gradient(135deg,#661FA5 0%,#9E38CC 100%)',width:280}}><div className='w-100 p-3 rounded-4' style={{border:'1px solid rgba(255,255,255,0.20)'}}><p className='fw-semibold mb-0'>Registry Analysis 2024: Trends in<br/><strong>Early Detection</strong></p></div></div></div></section>
<section className='py-5 mx-4 mb-4 rounded-3' style={{background:'linear-gradient(90deg,#611EA3 0%,#9E37CE 100%)'}}><h2 className='text-white fw-bold text-center mb-4'>Sponsor</h2><div className='row g-2 px-4'><div className='col-md-4'><div className='bg-white rounded-3 p-4 d-flex overflow-hidden' style={{minHeight:200}}><div className='d-flex align-items-center justify-content-center px-2 me-3 rounded-2' style={{background:'#E8E6F9',writingMode:'vertical-rl',transform:'rotate(180deg)',color:'#8805A4',fontWeight:700,fontSize:13,letterSpacing:1.5,textTransform:'uppercase',minHeight:120}}>WIA Cancer</div><div><h4 className='fw-bolder' style={{color:'#8805A4'}}>Sponsor</h4><p className='text-secondary small'>Explore our multidimensional clinical repository designed for precision oncology and longitudinal patient monitoring.</p></div></div></div>{[1,2,3,4,5].map(i=>(<div className='col' key={i}><div className='bg-white rounded-3 d-flex align-items-center justify-content-center' style={{minHeight:200}}><p style={{writingMode:'vertical-rl',textTransform:'uppercase',fontSize:11,fontWeight:700,letterSpacing:1,color:'#8805A4',padding:'16px 8px'}}>Cancer Institute (W.I.A)</p></div></div>))}</div></section>
<Footer />
</>
)
}